/// Global variables ///

// Dictionary for text conversion
const mathDictionary = {
    // Math operators
    "\\times" : "\u00D7",
    "\\rtimes" : "\u22CA",
    "\\ltimes" : "\u22C9",
    "\\div" : "\u00F7",
    "\\longdiv" : "\u27CC",
    "\\int" : "\u222B",
    "\\iint" : "\u222C",
    "\\iiint" : "\u222D",
    "\\iiiint" : "\u2A0C",
    "\\oint" : "\u222E",
    "\\oiint" : "\u222F",
    "\\oiiint" : "\u2230",
    "\\intclockwise" : "\u2231",
    "\\ointclockwise" : "\u2232",
    "\\ointctrclockwise" : "\u2233",
    "\\sqint" : "\u2A16",
    "\\fint" : "\u2A0F",
    "\\cupint" : "\u2A1A",
    "\\capint" : "\u2A19",
    "\\overbarint" : "\u2A1B",
    "\\underbarint" : "\u2A1C",
    "\\cupplus" : "\u228E",
    "\\timesint" : "\u2A18",
    "\\ast" : "\u2217",
    "\\star" : "\u22C6",
    "\\partial" : "\u2202",
    "\\nabla" : "\u2207",
    "\\sqrt" : "\u221A",
    "\\sqrt3" : "\u221B",
    "\\sqrt4" : "\u221C",
    "\\circ" : "\u2218",
    "\\sum" : "\u2211",
    "\\osum" : "\u2A0A",
    "\\sumint" : "\u2A0B",
    "\\prod" : "\u220F",
    "\\cdot" : "\u22C5",
    "\\pm" : "\u00B1",
    "\\mp" : "\u2213",
    "\\emptyset" : "\u2205",
    "\\sin" : "sin",
    "\\cos" : "cos",
    "\\tan" : "tan",
    "\\arcsin" : "arcsin",
    "\\arccos" : "arccos",
    "\\arctan" : "arctan",
    "\\cot" : "cot",
    "\\csc" : "csc",
    "\\sec" : "sec",
    "\\arccot" : "arccot",
    "\\arccsc" : "arccsc",
    "\\arcsec" : "arcsec",
    "\\*" : "*",
    "\\det" : "det",
    "\\log" : "log",
    "\\ln" : "ln",
    "\\lim" : "lim",
    "\\mod" : "mod",
    "\\cup" : "\u222A",
    "\\Cup" : "\u22D3",
    "\\sqcup" : "\u2294",
    "\\sqCup" : "\u2A4F",
    "\\cap" : "\u2229",
    "\\Cap" : "\u22D2",
    "\\sqcap" : "\u2293",
    "\\sqCap" : "\u2A4E",
    "\\uplus" : "\u228E",
    "\\def" : "\u225D",
    "\\vee" : "\u2228",
    "\\doublevee" : "\u2A56",
    "\\wedge" : "\u2227",
    "\\doublewedge" : "\u2A55",
    "\\curlyvee" : "\u22CE",
    "\\curlywedge" : "\u22CF",
    "\\diamond" : "\u22C4",
    "\\wr" : "\u2240",
    "\\oplus" : "\u2295",
    "\\ominus" : "\u2296",
    "\\otimes" : "\u2297",
    "\\oslash" : "\u2298",
    "\\odot" : "\u2299",
    "\\boxplus" : "\u229E",
    "\\boxminus" : "\u229F",
    "\\boxtimes" : "\u22A0",
    "\\boxdot" : "\u22A1",
    "\\amalg" : "\u2210",
    "\\tprime" : "\u2034",
    "\\lthree" : "\u22CB",
    "\\rthree" : "\u22CC",
    "\\pitchfork" : "\u22D4",
    "\\topfork" : "\u2ADA",

    // Fractions
    "\\frac" : "\u2215",  // Better suited for superscript over subscript
    "\\frac1/2" : "\u00BD",
    "\\frac1/7" : "⅐",
    "\\frac1/9" : "⅑",
    "\\frac1/10" : "⅒",
    "\\frac1/3"  :"⅓",
    "\\frac2/3" : "⅔",
    "\\frac1/5" : "⅕",
    "\\frac2/5" : "⅖",
    "\\frac3/5" : "⅗",
    "\\frac4/5" : "⅘",
    "\\frac1/6" : "⅙",
    "\\frac5/6" : "⅚",
    "\\frac1/8" : "⅛",
    "\\frac3/8" : "⅜",
    "\\frac5/8" : "⅝",
    "\\frac7/8" : "⅞",
    "\\fraca/c" : "\u2100",
    "\\fraca/s" : "\u2101",
    "\\fracc/o" : "\u2105",
    "\\fracc/u" : "\u2106",

    // Relations
    "\\forall" : "\u2200",
    "\\exists" : "\u2203",
    "\\nexists" : "\u2204",
    "\\land" : "\u2227",
    "\\lor" : "\u2228",
    "\\in" : "\u2208",
    "\\notin" : "\u2209",
    "\\ni" : "\u220B",
    "\\subset" : "\u2282",
    "\\nsubset" : "\u2284",
    "\\subseteq" : "\u2286",
    "\\nsubseteq" : "\u2288",
    "\\supset" : "\u2283",
    "\\nsupset" : "\u2285",
    "\\supseteq" : "\u2287",
    "\\nsupseteq" : "\u2289",
    "\\sqsubset" : "\u228F",
    "\\sqsupset" : "\u2290",
    "\\sqsubseteq" : "\u2291",
    "\\sqsupseteq" : "\u2292",
    "\\Subset" : "\u22D0",
    "\\Supset" : "\u22D1",
    "\\subsetplus" : "\u2ABF",
    "\\supsetplus" : "\u2AC0",
    "\\setminus" : "\u2216",
    "\\cong" : "\u2245",
    "\\ncong" : "\u2247",
    "\\propto" : "\u221D",
    "\\equiv" : "\u2261",
    "\\dotequiv" : "\u2A67",
    "\\superequiv" : "\u2263",
    "\\tbond" : "\u2261",
    "\\qbond" : "\u2263",
    "\\doteq" : "\u2250",
    "\\eqdot" : "\u2A66",
    "\\neq" : "\u2260",
    "\\approx" : "\u2248",
    "\\sim" : "\u223C",
    "\\simeq" : "\u224C",
    "\\nsim" : "\u2241",
    "\\nless" : "\u226E",
    "\\ngtr" : "\u226F",
    "\\leq" : "\u2264",
    "\\leqslant" : "\u2A7D",
    "\\geq" : "\u2265",
    "\\geqslant" : "\u2A7E",
    "\\nleq" : "\u2270",
    "\\ngeq" : "\u2271",
    "\\lneq" : "\u2A87",
    "\\lneqq" : "\u2268",
    "\\gneq" : "\u2A88",
    "\\gneqq" : "\u2269",
    "\\lnapprox" : "\u2A89",
    "\\gnapprox" : "\u2A8A",
    "\\lnsim" : "\u22E6",
    "\\gnsim" : "\u22E7",
    "\\ll" : "\u226A",
    "\\lll" : "\u22D8",
    "\\gg" : "\u226B",
    "\\ggg" : "\u22D9",
    "\\prec" : "\u227A",
    "\\succ" : "\u227B",
    "\\nprec" : "\u2280",
    "\\nsucc" : "\u2281",
    "\\preceq" : "\u227C",
    "\\succeq" : "\u227D",
    "\\precneqq" : "\u2AB5",
    "\\succneqq" : "\u2AB6",
    "\\precnapprox" : "\u2AB9",
    "\\succnapprox" : "\u2ABA",
    "\\precnsim" : "\u22E8",
    "\\succnsim" : "\u22E9",
    "\\perp" : "\u27C2",
    "\\Perp" : "\u2AEB",
    "\\parallel" : "\u2225",
    "\\nparallel" : "\u2226",
    "\\vvvert" : "\u2AF4",
    "\\nvvvert" : "\u2AF5",
    "\\nmid" : "\u2224",
    "\\asymp" : "\u224D",
    "\\neg" : "\u00AC",
    "\\bowtie" : "\u2A1D",
    "\\vdash" : "\u22A2",
    "\\nvdash" : "\u22AC",
    "\\dashv" : "\u22A3",
    "\\vDash" : "\u22A8",
    "\\Dashv" : "\u2AE4",
    "\\nvDash" : "\u22AD",
    "\\Vdash" : "\u22A9",
    "\\dashV" : "\u2AE3",
    "\\nVdash" : "\u22AE",
    "\\VDash" : "\u22AB",
    "\\DashV" : "\u2AE5",
    "\\nVDash" : "\u22AF",
    "\\triangleleft" : "\u22B2",
    "\\ntriangleleft" : "\u22EA",
    "\\triangleright" : "\u22B3",
    "\\ntriangleright" : "\u22EB",
    "\\ntrianglelefteq" : "\u22EC",
    "\\ntrianglerighteq" : "\u22ED",
    "\\triangleq" : "\u225C",
    "\\equest" : "\u225F",
    "\\lquest" : "\u2A7B",
    "\\rquest" : "\u2A7C",
    "\\mquest" : "\u225E",
    "\\vdots" : "\u22EE",
    "\\cdots" : "\u22EF",
    "\\udots" : "\u22F0",
    "\\ddots" : "\u22F1",
    "\\ldots" : "\u2026",
    "\\top" : "\u22A4",
    "\\bot" : "\u22A5",
    "\\between" : "\u226C",
    "\\therefore" : "\u2234",
    "\\because" : "\u2235",
    "\\squaredots" : "\u2237",
    "\\dotminus" : "\u2238",
    "\\max" : "max",
    "\\min" : "min",

    // Arrows
    "\\Rightarrow" : "\u21D2",
    "\\=>" : "\u21D2",
    "\\Leftarrow" : "\u21D0",
    "\\<=" : "\u21D0",
    "\\nLeftarrow" : "\u21CD",
    "\\nRightarrow" : "\u21CF",
    "\\nLeftrightarrow" : "\u21CE",
    "\\<=>" : "\u21D4",
    "\\Uparrow" : "\u21D1",
    "\\Downarrow" : "\u21D3",
    "\\Updownarrow" : "\u21D5",
    "\\rightarrow" : "\u2192",
    "\\->" : "\u2192",
    "\\longrightarrow" : "\u27F6",
    "\\-->" : "\u27F6",
    "\\leftarrow" : "\u2190",
    "\\<-" : "\u2190",
    "\\leftrightarrow" : "\u2194",
    "\\<->" : "\u2194",
    "\\nleftrightarrow" : "\u21AE",
    "\\uparrow" : "\u2191",
    "\\downarrow" : "\u2193",
    "\\updownarrow" : "\u2195",
    "\\nleftarrow" : "\u219A",
    "\\nrightarrow" : "\u219B",
    "\\Longleftarrow" : "\u27F8",
    "\\implies" : "\u27F9",
    "\\Leftrightarrow" : "\u21D4",
    "\\iff" : "\u27FA",
    "\\mapsto" : "\u27FC",
    "\\rightleftharpoons" : "\u21CC",
    "\\leftrightharpoons" : "\u21CB",
    "\\rightharpoonup" : "\u21C0",
    "\\rightharpoondown" : "\u21C1",
    "\\leftharpoonup" : "\u21BC",
    "\\leftharpoondown" : "\u21BD",
    "\\upharpoonleft" : "\u21BF",
    "\\upharpoonright" : "\u21BE",
    "\\downharpoonleft" : "\u21C3",
    "\\downharpoonright" : "\u21C2", 
    "\\hookleftarrow" : "\u21A9",
    "\\hookrightarrow" : "\u21AA",
    "\\nearrow" : "\u2197",
    "\\searrow" : "\u2198",
    "\\swarrow" : "\u2199",
    "\\nwarrow" : "\u2196",
    "\\twoheadleftarrow" : "\u219E",
    "\\twoheadrightarrow" : "\u21A0",
    "\\twoheaduparrow" : "\u219F",
    "\\twoheaddownarrow" : "\u21A1",
    "\\Lsh" : "\u21B0",
    "\\Rsh" : "\u21B1",
    "\\leftleftarrows" : "\u21C7",
    "\\rightrightarrows" : "\u21C9",
    "\\upuparrows" : "\u21C8",
    "\\downdownarrows" : "\u21CA",
    "\\leftrightarrows" : "\u21C6",
    "\\rightleftarrows" : "\u21C4",
    "\\Lleftarrow" : "\u21DA",
    "\\Rrightarrow" : "\u21DB",
    "\\leftarrowtail" : "\u21A2",
    "\\rightarrowtail" : "\u21A3",
    "\\leftsquigarrow" : "\u21DC",
    "\\rightsquigarrow" : "\u21DD",
    "\\leftrightsquigarrow" : "\u21AD",
    "\\looparrowleft" : "\u21AB",
    "\\looparrowright" : "\u21AC",
    "\\circlearrowleft" : "\u21BA",
    "\\circlearrowright" : "\u21BB",
    "\\curvearrowleft" : "\u21B6",
    "\\curvearrowright" : "\u21B7",

    // Greek alphabet
    "\\alpha" : "\u{1D6FC}",
    "\\beta" : "\u{1D6FD}",
    "\\Gamma" : "\u{1D6E4}",
    "\\gamma" : "\u{1D6FE}",
    "\\Delta" : "\u0394",
    "\\delta" : "\u03B4",
    "\\epsilon" : "\u03F5",
    "\\varepsilon" : "\u03B5",
    "\\zeta" : "\u03B6",
    "\\eta" : "\u{1D702}",
    "\\Theta" : "\u0398",
    "\\theta" : "\u{1D703}",
    "\\vartheta" : "\u03D1",
    "\\iota" : "\u{1D704}",
    "\\kappa" : "\u{1D705}",
    "\\varkappa" : "\u{1D718}",
    "\\Lambda" : "\u039B",
    "\\lambda" : "\u03BB",
    "\\mu" : "\u{1D707}",
    "\\nu" : "\u{1D708}",
    "\\Xi" : "\u039E",
    "\\xi" : "\u{1D709}",
    "\\Pi" : "\u03A0",
    "\\pi" : "\u{1D70B}",
    "\\varpi" : "\u{1D71B}",
    "\\rho" : "\u{1D70C}",
    "\\varrho" : "\u03F1",
    "\\Sigma" : "\u03A3",
    "\\sigma" : "\u03C3",
    "\\varsigma" : "\u03C2",
    "\\tau" : "\u{1D70F}",
    "\\Upsilon" : "\u{1D6F6}",
    "\\upsilon" : "\u{1D710}",
    "\\Phi" : "\u03A6",
    "\\phi" : "\u{1D719}",
    "\\varphi" : "\u{1D711}",
    "\\chi" : "\u{1D712}",
    "\\Psi" : "\u{1D6F9}",
    "\\psi" : "\u{1D713}",
    "\\Omega" : "\u2126",
    "\\omega" : "\u{1D714}",

    // Mathbb
    "\\mathbbA" : "\u{1D538}",
    "\\mathbbB" : "\u{1D539}",
    "\\mathbbC" : "\u2102",
    "\\mathbbD" : "\u{1D53B}",
    "\\mathbbE" : "\u{1D53C}",
    "\\mathbbF" : "\u{1D53D}",
    "\\mathbbG" : "\u{1D53E}",
    "\\mathbbH" : "\u210D",
    "\\mathbbI" : "\u{1D540}",
    "\\mathbbJ" : "\u{1D541}",
    "\\mathbbK" : "\u{1D542}",
    "\\mathbbL" : "\u{1D543}",
    "\\mathbbM" : "\u{1D544}",
    "\\mathbbN" : "\u2115",
    "\\mathbbO" : "\u{1D546}",
    "\\mathbbP" : "\u2119",
    "\\mathbbQ" : "\u211A",
    "\\mathbbR" : "\u211D",
    "\\mathbbS" : "\u{1D54A}",
    "\\mathbbT" : "\u{1D54B}",
    "\\mathbbU" : "\u{1D54C}",
    "\\mathbbV" : "\u{1D54D}",
    "\\mathbbW" : "\u{1D54E}",
    "\\mathbbX" : "\u{1D54F}",
    "\\mathbbY" : "\u{1D550}",
    "\\mathbbZ" : "\u2124",
    "\\mathbba" : "\u{1D552}",
    "\\mathbbb" : "\u{1D553}",
    "\\mathbbc" : "\u{1D554}",
    "\\mathbbd" : "\u{1D555}",
    "\\mathbbe" : "\u{1D556}",
    "\\mathbbf" : "\u{1D557}",
    "\\mathbbg" : "\u{1D558}",
    "\\mathbbh" : "\u{1D559}",
    "\\mathbbi" : "\u{1D55A}",
    "\\mathbbj" : "\u{1D55B}",
    "\\mathbbk" : "\u{1D55C}",
    "\\mathbbl" : "\u{1D55D}",
    "\\mathbbm" : "\u{1D55E}",
    "\\mathbbn" : "\u{1D55F}",
    "\\mathbbo" : "\u{1D560}",
    "\\mathbbp" : "\u{1D561}",
    "\\mathbbq" : "\u{1D562}",
    "\\mathbbr" : "\u{1D563}",
    "\\mathbbs" : "\u{1D564}",
    "\\mathbbt" : "\u{1D565}",
    "\\mathbbu" : "\u{1D566}",
    "\\mathbbv" : "\u{1D567}",
    "\\mathbbw" : "\u{1D568}",
    "\\mathbbx" : "\u{1D569}",
    "\\mathbby" : "\u{1D56A}",
    "\\mathbbz" : "\u{1D56B}",
    
    "\\mathbbpi" : "\u213C",
    "\\mathbbPi" : "\u213F",
    "\\mathbbgamma" : "\u213D",
    "\\mathbbGamma" : "\u213E",
    "\\mathbbSigma" : "\u2140",

    "\\mathbb0" : "\u{1D7D8}",
    "\\mathbb1" : "\u{1D7D9}",
    "\\mathbb2" : "\u{1D7DA}",
    "\\mathbb3" : "\u{1D7DB}",
    "\\mathbb4" : "\u{1D7DC}",
    "\\mathbb5" : "\u{1D7DD}",
    "\\mathbb6" : "\u{1D7DE}",
    "\\mathbb7" : "\u{1D7DF}",
    "\\mathbb8" : "\u{1D7E0}",
    "\\mathbb9" : "\u{1D7E1}",

    // Mathbf
    "\\mathbfA" : "\u{1D468}",
    "\\mathbfa" : "\u{1D482}",
    "\\mathbfB" : "\u{1D469}",
    "\\mathbfb" : "\u{1D483}",
    "\\mathbfC" : "\u{1D46A}",
    "\\mathbfc" : "\u{1D484}",
    "\\mathbfD" : "\u{1D46B}",
    "\\mathbfd" : "\u{1D485}",
    "\\mathbfE" : "\u{1D46C}",
    "\\mathbfe" : "\u{1D486}",
    "\\mathbfF" : "\u{1D46D}",
    "\\mathbff" : "\u{1D487}",
    "\\mathbfG" : "\u{1D46E}",
    "\\mathbfg" : "\u{1D488}",
    "\\mathbfH" : "\u{1D46F}",
    "\\mathbfh" : "\u{1D489}",
    "\\mathbfI" : "\u{1D470}",
    "\\mathbfi" : "\u{1D48A}",
    "\\mathbfJ" : "\u{1D471}",
    "\\mathbfj" : "\u{1D48B}",
    "\\mathbfK" : "\u{1D472}",
    "\\mathbfk" : "\u{1D48C}",
    "\\mathbfL" : "\u{1D473}",
    "\\mathbfl" : "\u{1D48D}",
    "\\mathbfM" : "\u{1D474}",
    "\\mathbfm" : "\u{1D48E}",
    "\\mathbfN" : "\u{1D475}",
    "\\mathbfn" : "\u{1D48F}",
    "\\mathbfO" : "\u{1D476}",
    "\\mathbfo" : "\u{1D490}",
    "\\mathbfP" : "\u{1D477}",
    "\\mathbfp" : "\u{1D491}",
    "\\mathbfQ" : "\u{1D478}",
    "\\mathbfq" : "\u{1D492}",
    "\\mathbfR" : "\u{1D479}",
    "\\mathbfr" : "\u{1D493}",
    "\\mathbfS" : "\u{1D47A}",
    "\\mathbfs" : "\u{1D494}",
    "\\mathbfT" : "\u{1D47B}",
    "\\mathbft" : "\u{1D495}",
    "\\mathbfU" : "\u{1D47C}",
    "\\mathbfu" : "\u{1D496}",
    "\\mathbfV" : "\u{1D47D}",
    "\\mathbfv" : "\u{1D497}",
    "\\mathbfW" : "\u{1D47E}",
    "\\mathbfw" : "\u{1D498}",
    "\\mathbfX" : "\u{1D47F}",
    "\\mathbfx" : "\u{1D499}",
    "\\mathbfY" : "\u{1D480}",
    "\\mathbfy" : "\u{1D49A}",
    "\\mathbfZ" : "\u{1D481}",
    "\\mathbfz" : "\u{1D49B}",

    "\\mathbf0" : "\u{1D7EC}",
    "\\mathbf1" : "\u{1D7ED}",
    "\\mathbf2" : "\u{1D7EE}",
    "\\mathbf3" : "\u{1D7EF}",
    "\\mathbf4" : "\u{1D7F0}",
    "\\mathbf5" : "\u{1D7F1}",
    "\\mathbf6" : "\u{1D7F2}",
    "\\mathbf7" : "\u{1D7F3}",
    "\\mathbf8" : "\u{1D7F4}",
    "\\mathbf9" : "\u{1D7F5}",

    "\\mathbfalpha" : "\u{1D736}",
    "\\mathbfbeta" : "\u{1D737}",
    "\\mathbfGamma" : "\u{1D71E}",
    "\\mathbfgamma" : "\u{1D738}",
    "\\mathbfDelta" : "\u{1D6AB}",
    "\\mathbfdelta" : "\u{1D6C5}",
    "\\mathbfepsilon" : "\u{1D6DC}",
    "\\mathbfvarepsilon" : "\u{1D6C6}",
    "\\mathbfzeta" : "\u{1D6C7}",
    "\\mathbfeta" : "\u{1D73C}",
    "\\mathbfTheta" : "\u{1D6BD}",
    "\\mathbftheta" : "\u{1D73D}",
    "\\mathbfvartheta" : "\u{1D6DD}",
    "\\mathbfiota" : "\u{1D73E}",
    "\\mathbfkappa" : "\u{1D73F}",
    "\\mathbfvarkappa" : "\u{1D752}",
    "\\mathbfLambda" : "\u{1D6B2}",
    "\\mathbflambda" : "\u{1D6CC}",
    "\\mathbfmu" : "\u{1D741}",
    "\\mathbfnu" : "\u{1D742}",
    "\\mathbfXi" : "\u{1D6B5}",
    "\\mathbfxi" : "\u{1D743}",
    "\\mathbfPi" : "\u{1D6B7}",
    "\\mathbfpi" : "\u{1D745}",
    "\\mathbfvarpi" : "\u{1D755}",
    "\\mathbfrho" : "\u{1D746}",
    "\\mathbfvarrho" : "\u{1D6E0}",
    "\\mathbfSigma" : "\u{1D6BA}",
    "\\mathbfsigma" : "\u{1D6D4}",
    "\\mathbfvarsigma" : "\u{1D6D3}",
    "\\mathbftau" : "\u{1D749}",
    "\\mathbfUpsilon" : "\u{1D730}",
    "\\mathbfupsilon" : "\u{1D74A}",
    "\\mathbfPhi" : "\u{1D6BD}",
    "\\mathbfphi" : "\u{1D753}",
    "\\mathbfvarphi" : "\u{1D74B}",
    "\\mathbfchi" : "\u{1D74C}",
    "\\mathbfPsi" : "\u{1D733}",
    "\\mathbfpsi" : "\u{1D74D}",
    "\\mathbfOmega" : "\u{1D6C0}",
    "\\mathbfomega" : "\u{1D74E}",

    // For Lewis Notation
    "\\above." : "\u0307",
    "\\below." : "\u0323",
    "\\above:" : "\u0308",
    "\\below:" : "\u0324",
    "\\mid." : "\u2E31",
    "\\mid:" : "\u003A",

    // Chess
    "\\wking" : "\u2654",
    "\\wqueen" : "\u2655",
    "\\wrook" : "\u2656",
    "\\wbishop" : "\u2657",
    "\\wknight" :"\u2658",
    "\\wpawn" : "\u2659",
    "\\bking" : "\u265A",
    "\\bqueen" : "\u265B",
    "\\brook" : "\u265C",
    "\\bbishop" : "\u265D",
    "\\bknight" :"\u265E",
    "\\bpawn" : "\u265F",

    // Card games
    "\\bspade" : "\u2660",
    "\\wheart" : "\u2661",
    "\\wdiamond" : "\u2662",
    "\\bclub" : "\u2663",
    "\\wspade" : "\u2664",
    "\\bheart" : "\u2665",
    "\\bdiamond" : "\u2666",
    "\\wclub" : "\u2667",

    // Money
    "\\dollar" : "\u0024",
    "\\cent" : "\u00A2",
    "\\pound" : "\u00A3",
    "\\yen" : "\u00A5",
    "\\franc" : "\u20A3",
    "\\euro" : "\u20AC",
    "\\peso" : "\u20B1",
    "\\bitcoin" : "\u20BF",
    "\\austral" : "\u20B3",
    "\\ruble" : "\u20BD",
    "\\hryvnia" : "\u20B4",
    "\\rupee" : "\u20B9",
    "\\lira" : "\u20AA",
    "\\tlira" : "\u20A9",
    "\\won" : "\u20A9",
    "\\baht" : "\u0E3F",

    // Non italic letters
    "\\A" : "A",
    "\\a" : "a",
    "\\B" : "B",
    "\\b" : "b",
    "\\C" : "C",
    "\\c" : "c",
    "\\D" : "D",
    "\\d" : "d",
    "\\E" : "E",
    "\\e" : "e",
    "\\F" : "F",
    "\\f" : "f",
    "\\G" : "G",
    "\\g" : "g",
    "\\H" : "H",
    "\\h" : "h",
    "\\I" : "I",
    "\\i" : "i",
    "\\J" : "J",
    "\\j" : "j",
    "\\K" : "K",
    "\\k" : "k",
    "\\L" : "L",
    "\\l" : "l",
    "\\M" : "M",
    "\\m" : "m",
    "\\N" : "N",
    "\\n" : "n",
    "\\O" : "O",
    "\\o" : "o",
    "\\P" : "P",
    "\\p" : "p",
    "\\Q" : "Q",
    "\\q" : "q",
    "\\R" : "R",
    "\\r" : "r",
    "\\S" : "S",
    "\\s" : "s",
    "\\T" : "T",
    "\\t" : "t",
    "\\U" : "U",
    "\\u" : "u",
    "\\V" : "V",
    "\\v" : "v",
    "\\W" : "W",
    "\\w" : "w",
    "\\X" : "X",
    "\\x" : "x",
    "\\Y" : "Y",
    "\\y" : "y",
    "\\Z" : "Z",
    "\\z" : "z",
    
    // Combining
    "\\overline" : "\u0305",
    "\\underline" : "\u0332",
    "\\ooverline" : "\u035E",
    "\\uunderline" : "\u035F",
    "\\overfrown" : "\u0361",
    "\\oversmile" : "\u035D",
    "\\undersmile" : "\u035C",
    "\\hat" : "\u0302",
    "\\not" : "\u0338",
    "\\tilde" : "\u0303",
    "\\ttilde" : "\u0360",
    "\\vec" : "\u20D7",
    "\\overinf" : "\u1AB2",  // Only works on certain website/apps

    "\\overa" : "\u0363",
    "\\overc" : "\u0368",
    "\\overd" : "\u0369",
    "\\overe" : "\u0364",
    "\\overh" : "\u036A",
    "\\overi" : "\u0365",
    "\\overk" : "\u1DDC",  // Only works on certain website/apps
    "\\overm" : "\u036B",
    "\\overn" : "\u1DE0",  // Only works on certain website/apps
    "\\overo" : "\u0366",
    "\\overr" : "\u036C",
    "\\overt" : "\u036D",
    "\\overu" : "\u0367",
    "\\overv" : "\u036E",
    "\\overx" : "\u036F",

    // Greek subscript and superscript
    "\\^beta" : "\u1D5D",
    "\\^Gamma" : "ᣘ",
    "\\^gamma" : "\u1D5E",
    "\\^Delta" : "ᐞ",
    "\\^delta" : "\u1D5F",
    "\\^epsilon" : "ᵋ",
    "\\^Lambda" : "ᣔ",
    "\\^theta" : "\u1DBF",
    "\\^iota" : "ᶥ",
    "\\^nu" : "ᶹ",
    "\\^phi" : "\u1D60",
    "\\^chi" : "\u1D61",

    "\\_beta" : "\u1D66",
    "\\_gamma" : "\u1D67",
    "\\_rho" : "\u1D68",
    "\\_phi" : "\u1D69",
    "\\_chi" : "\u1D6A",

    "\\^int" : "ᶴ",

    // Music
    "\\flat" : "\u{1D12C}",
    "\\natural" : "\u{1D12E}",
    "\\sharp" : "\u{1D130}",
    "\\eightnote" : "\u{1D160}",
    "\\sixteenthnote" : "\u{1D161}",
    "\\halfnote" : "\u{1D15E}",
    "\\quarternote" : "\u{1D15F}",
    "\\fullnote" : "\u{1D15D}",
    "\\doublenote" : "\u266B",
    "\\trebleclef" : "\u{1D11E}",

    // Other symbols
    "\\infty" : "\u221E",
    "\\iinfin" : "\u29DC",
    "\\tieinfty" : "\u29DD",
    "\\nvinfty" : "\u29DE",
    "\\acidfree" : "\u267E",
    "\\angle" : "\u2220",
    "\\measuredangle" : "\u2221",
    "\\sphericalangle" : "\u2222",
    "\\rightangle" : "\u299C",
    "\\hbar" : "\u210F",
    "\\ell" : "\u2113",
    "\\dagger" : "\u2020",
    "\\ddagger" : "\u2021",
    "\\qc" : "\u269C",
    "\\section" : "\u00A7",
    "\\paragraph" : "\u00B6",
    "\\copyright" : "\u00A9",
    "\\registered" : "\u00AE",
    "\\wp" : "\u2118",
    "\\emdash" : "\u2014",
    "\\bullet" : "\u25CF",
    "\\langle" : "\u27E8",
    "\\rangle" : "\u27E9",
    "\\llangle" : "\u27EA",
    "\\rrangle" : "\u27EB",
    "\\lceil" : "\u2308",
    "\\rceil" : "\u2309",
    "\\lfloor" : "\u230A",
    "\\rfloor" : "\u230B",
    "\\lBrace" : "\u2983",
    "\\rBrace" : "\u2984",
    "\\llbracket" : "\u27E6",
    "\\rrbracket" : "\u27E7",
    "\\llparenthesis" : "\u2985",
    "\\rrparenthesis" : "\u2986",
    "\\frown" : "\u2322",
    "\\smile" : "\u2323",
    "\\qed" : "\u220E",
    "\\male" : "\u2642",
    "\\female" : "\u2640",
    "\\Hermaphrodite" : "\u26A5",
    "\\neuter" : "\u26B2",
    "\\malemale" : "\u26A3",
    "\\femalefemale" : "\u26A2",
    "\\femalemale" : "\u26A4",
    "\\" : "\\",
    "\\:" : "\\:",
    "\\colon" : "\u003A",
    "\\\\" : "\u000A",
    "\\tab" : "\u0009"
};

const lettersSymbols = {
    "\u000A" : "", // Cancels the line skipped by pressing "enter", use "\\" instead
    "+" : "\u002B",
    "-" : "\u2212",
    "=" : "\u003D",
    "'" : "\u2032",
    '"' : "\u2033",
    "/" : "/",
    "\\" : "\\",
    "," : ",",
    "." : ".",
    "°" : "°",
    "|" : "|",
    "!" : "!",
    "?" : "?",
    "&" : "&",
    "(" : "(",
    ")" : ")",
    "{" : "{",
    "}" : "}",
    "[" : "[",
    "]" : "]",
    "<" : "\u003C",
    ">" : "\u003E",
    "^" : "^",
    "_" : "_",
    "%" : "%",
    "#" : "#",
    ":" : "\u2236",
    ";" : ";",
    "0" : "0",
    "1" : "1",
    "2" : "2",
    "3" : "3",
    "4" : "4",
    "5" : "5",
    "6" : "6",
    "7" : "7",
    "8" : "8",
    "9" : "9", 
    "A" : "\u{1D434}",
    "a" : "\u{1D44E}",
    "B" : "\u{1D435}",
    "b" : "\u{1D44F}",
    "C" : "\u{1D436}",
    "c" : "\u{1D450}",
    "D" : "\u{1D437}",
    "d" : "\u{1D451}",
    "E" : "\u{1D438}",
    "e" : "\u{1D452}",
    "F" : "\u{1D439}",
    "f" : "\u{1D453}",
    "G" : "\u{1D43A}",
    "g" : "\u{1D454}",
    "H" : "\u{1D43B}",
    "h" : "\u210E",
    "I" : "\u{1D43C}",
    "i" : "\u{1D456}",
    "J" : "\u{1D43D}",
    "j" : "\u{1D457}",
    "K" : "\u{1D43E}",
    "k" : "\u{1D458}",
    "L" : "\u{1D43F}",
    "l" : "\u{1D459}",
    "M" : "\u{1D440}",
    "m" : "\u{1D45A}",
    "N" : "\u{1D441}",
    "n" : "\u{1D45B}",
    "O" : "\u{1D442}",
    "o" : "\u{1D45C}",
    "P" : "\u{1D443}",
    "p" : "\u{1D45D}",
    "Q" : "\u{1D444}",
    "q" : "\u{1D45E}",
    "R" : "\u{1D445}",
    "r" : "\u{1D45F}",
    "S" : "\u{1D446}",
    "s" : "\u{1D460}",
    "T" : "\u{1D447}",
    "t" : "\u{1D461}",
    "U" : "\u{1D448}",
    "u" : "\u{1D462}",
    "V" : "\u{1D449}",
    "v" : "\u{1D463}",
    "W" : "\u{1D44A}",
    "w" : "\u{1D464}",
    "X" : "\u{1D44B}",
    "x" : "\u{1D465}",
    "Y" : "\u{1D44C}",
    "y" : "\u{1D466}",
    "Z" : "\u{1D44D}",
    "z" : "\u{1D467}"
};

const subscript = {
    "_" : "",
    "0" : "\u2080",
    "1" : "\u2081",
    "2" : "\u2082",
    "3" : "\u2083",
    "4" : "\u2084",
    "5" : "\u2085",
    "6" : "\u2086",
    "7" : "\u2087",
    "8" : "\u2088",
    "9" : "\u2089",
    "+" : "\u208A",
    "-" : "\u208B",
    "=" : "\u208C",
    "(" : "\u208D",
    ")" : "\u208E",
    "a" : "\u2090",
    "e" : "\u2091",
    "h" : "\u2095",
    "i" : "\u1D62",
    "j" : "ⱼ",
    "k" : "\u2096",
    "l" : "\u2097",
    "m" : "\u2098",
    "n" : "\u2099",
    "o" : "\u2092",
    "p" : "\u209A",
    "r" : "ᵣ",
    "s" : "\u209B",
    "t" : "\u209C",
    "u" : "ᵤ",
    "v" : "ᵥ",
    "x" : "\u2093",
};

const superscript = {
    "^" : "",
    "0" : "\u2070",
    "1" : "\u00B9",
    "2" : "\u00B2",
    "3" : "\u00B3",
    "4" : "\u2074",
    "5" : "\u2075",
    "6" : "\u2076",
    "7" : "\u2077",
    "8" : "\u2078",
    "9" : "\u2079",
    "+" : "\u207A",
    "-" : "\u207B",
    "=" : "\u207C",
    "(" : "\u207D",
    ")" : "\u207E",
    "\\" : "ᐠ",
    "/" : "ᐟ",
    "A" : "ᴬ",
    "a" : "ᵃ",
    "B" : "ᴮ",
    "b" : "ᵇ",
    "c" : "ᶜ",
    "D" : "ᴰ",
    "d" : "ᵈ",
    "E" : "ᴱ",
    "e" : "ᵉ",
    "f" : "ᶠ",
    "G" : "ᴳ",
    "g" : "ᵍ",
    "H" : "ᴴ",
    "h" : "ʰ",
    "I" : "ᴵ",
    "i" : "ⁱ",
    "J" : "ᴶ",
    "j" : "ʲ",
    "K" : "ᴷ",
    "k" : "ᵏ",
    "L" : "ᴸ",
    "l" : "ˡ",
    "M" : "ᴹ",
    "m" : "ᵐ",
    "N" : "ᴺ",
    "n" : "ⁿ",
    "O" : "ᴼ",
    "o" : "ᵒ",
    "P" : "ᴾ",
    "p" : "ᵖ",
    "R" : "ᴿ",
    "r" : "ʳ",
    "s" : "ˢ",
    "T" : "ᵀ",
    "t" : "ᵗ",
    "U" : "ᵁ",
    "u" : "ᵘ",
    "V" : "ⱽ",
    "v" : "ᵛ",
    "W" : "ᵂ",
    "w" : "ʷ",
    "x" : "ˣ",
    "y" : "ʸ",
    "z" : "ᶻ"
};

const lettersChem = {
    "\u000A" : "", // Cancels the line skipped by pressing "enter", use "\\" instead
    "+" : "\u002B",
    "-" : "\u2212",
    "=" : "\u003D",
    "'" : "\u2032",
    '"' : "\u2033",
    "/" : "/",
    "\\" : "\\",
    "," : ",",
    "." : ".",
    "°" : "°",
    "|" : "|",
    "!" : "!",
    "?" : "?",
    "&" : "&",
    "(" : "(",
    ")" : ")",
    "{" : "{",
    "}" : "}",
    "[" : "[",
    "]" : "]",
    "<" : "\u003C",
    ">" : "\u003E",
    "^" : "^",
    "_" : "_",
    "%" : "%",
    "#" : "#",
    ":" : ":",
    ";" : ";",
    "0" : "0",
    "1" : "1",
    "2" : "2",
    "3" : "3",
    "4" : "4",
    "5" : "5",
    "6" : "6",
    "7" : "7",
    "8" : "8",
    "9" : "9", 
    "A" : "A",
    "a" : "a",
    "B" : "B",
    "b" : "b",
    "C" : "C",
    "c" : "c",
    "D" : "D",
    "d" : "d",
    "E" : "E",
    "e" : "e",
    "F" : "F",
    "f" : "f",
    "G" : "G",
    "g" : "g",
    "H" : "H",
    "h" : "h",
    "I" : "I",
    "i" : "i",
    "J" : "J",
    "j" : "j",
    "K" : "K",
    "k" : "k",
    "L" : "L",
    "l" : "l",
    "M" : "M",
    "m" : "m",
    "N" : "N",
    "n" : "n",
    "O" : "O",
    "o" : "o",
    "P" : "P",
    "p" : "p",
    "Q" : "Q",
    "q" : "q",
    "R" : "R",
    "r" : "r",
    "S" : "S",
    "s" : "s",
    "T" : "T",
    "t" : "t",
    "U" : "U",
    "u" : "u",
    "V" : "V",
    "v" : "v",
    "W" : "W",
    "w" : "w",
    "X" : "X",
    "x" : "x",
    "Y" : "Y",
    "y" : "y",
    "Z" : "Z",
    "z" : "z",
};

// Submit button
const submit = document.getElementById("button");
submit.onclick = function() {main()};

// Copy button
const copyButton = document.getElementById("copy");
copyButton.onclick = function () {copy()};

// Clear button
const resetButton = document.getElementById("reset");
resetButton.onclick = function () {clear()};

// Every undefined commands
let errorsList = "";



/// FUNCTIONS ///

// Copy to clipboard
function copy() {
    const copyText = document.getElementById("text_out");
    navigator.clipboard.writeText(copyText.value);
    copyButton.value = "Copied!";
    copyButton.style.cursor = "default";

    setTimeout(() => {
        copyButton.value = "Copy text";
        copyButton.style.cursor = "pointer";
    }, 3000)  // Returns to initial copyButton
};

// Clears "Text copied!"
function clear() {
    copyButton.value = "Copy text";
    copyButton.style.cursor = "pointer";
    document.getElementById("mistakes").textContent = "";
};

// Remove space
function removeSpace(text) {
    const checkedButton = document.getElementById("remove");
    if (checkedButton.checked == true) {
        text = text.replace(/ /g, "");
        text = text.replace(/\=/g, " \= ");
        text = text.replace(/\u27F9/g, " \u27F9 ");
    };
    return text;
};

// Add spaces
function spaceCommand(text) {
    text = text.replace(/\\:/g, " ");
    return text;
};

// Takes word and replace letter by letter in the dictionary
function replaceLetters(word, dictionary) {
    let i;
    let newWord = "";
    for (i in word) {
        newWord += word[i].replace(word[i], dictionary[word[i]]);
    };
    return newWord;
};

// Chemistry package
function chemistry(words, newText) {
    let i;
    for (i in words) {
        let firstLetter = words[i].charAt(0);
        if (firstLetter == "\\") {
            newText = newText.replace(words[i], mathDictionary[words[i]]);
            mistakes(words[i], mathDictionary[words[i]]);
        } else if (firstLetter == "_") {
            newText = newText.replace(words[i], replaceLetters(words[i], subscript));
            mistakes(words[i], replaceLetters(words[i], subscript));
        } else if (firstLetter == "^") {
            newText = newText.replace(words[i], replaceLetters(words[i], superscript));
            mistakes(words[i], replaceLetters(words[i], superscript));
        } else {
            newText = newText.replace(words[i], replaceLetters(words[i], lettersChem));
            mistakes(words[i], replaceLetters(words[i], lettersChem));
        };
    };
    return newText;
};

// Adjust the spaces for the Chemistry package
function adjustSpaceChem(text) {
    text = text.replace(/ /g, "");
    text = text.replace(/\+/g, " + ");
    text = text.replace(/\u27F6/g, " \u27F6 ");
    text = text.replace(/\u21CC/g, " \u21CC ");
    text = text.replace(/\u21CB/g, " \u21CB ");
    text = text.replace(/\u21C0/g, " \u21C0 ");
    text = text.replace(/\u21C1/g, " \u21C1 ");
    text = text.replace(/\u21BC/g, " \u21BC ");
    text = text.replace(/\u21BD/g, " \u21BD ");
    return text;
};

// Changes "undefined" to "err"
function errors(text) {
    const err = "\u{1D41E}\u0353\u{1D42B}\u0353\u{1D42B}"; // bold "err" with two "x" under it
    text = text.replace(/undefined/g, err);
    return text;
};

// Writes every errors in a box, so it's easier to find them
function mistakes(textInput, textOutput) {
    const popup = document.getElementById("mistakes");
    const text = "<span id='errorsTitle'>Errors: </span><br>";
    if (textOutput === undefined) {
        errorsList += '"' + textInput + '" <br>';
    };
    if (errorsList.length > 0) {
        popup.innerHTML = text + errorsList;
        
        popup.style.fontFamily = "Times New Roman";
        popup.style.fontSize = "15px";
        const errorsTitleStyle = document.getElementById("errorsTitle").style;
        errorsTitleStyle.fontWeight = "bold";
    };
};

// Takes text and convert word by word in the dictionary or in function replaceLetters
function convert(words, newText) {
    let i;
    if (words[0] == "$chem") {
        newText = newText.replace("$chem", "");
        newText = chemistry(words, newText);
        newText = adjustSpaceChem(newText);
    } else {
    for (i in words) {
        let firstLetter = words[i].charAt(0);
        if (firstLetter == "\\") {
            newText = newText.replace(words[i], mathDictionary[words[i]]);
            mistakes(words[i], mathDictionary[words[i]]);
        } else if (firstLetter == "_") {
            newText = newText.replace(words[i], replaceLetters(words[i], subscript));
            mistakes(words[i], replaceLetters(words[i], subscript));
        } else if (firstLetter == "^") {
            newText = newText.replace(words[i], replaceLetters(words[i], superscript));
            mistakes(words[i], replaceLetters(words[i], superscript));
        } else {
            newText = newText.replace(words[i], replaceLetters(words[i], lettersSymbols));
            mistakes(words[i], replaceLetters(words[i], lettersSymbols));
        };
    };
    newText = removeSpace(newText);
    };
    newText = errors(newText);
    return newText;
};

// Takes the original text and spits out the new one
function main() {

    document.getElementById("mistakes").innerHTML = "";  // Starts with an empty box for errors
    errorsList = "";  // Makes sure it starts empty

    const fullText = document.text_input.text_in.value;
    const words = fullText.split(" ");
    let newText = fullText;

    newText = convert(words, newText);
    newText = spaceCommand(newText);
    document.text_input.text_out.value = newText;
    document.getElementById("text_out").disabled = false;

};

